// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEFMigrationsHistory = "__EFMigrationsHistory"

// EFMigrationsHistory mapped from table <__EFMigrationsHistory>
type EFMigrationsHistory struct {
	MigrationID    string `gorm:"column:MigrationId;type:character varying(150);primaryKey" json:"MigrationId"`
	ProductVersion string `gorm:"column:ProductVersion;type:character varying(32);not null" json:"ProductVersion"`
}

// TableName EFMigrationsHistory's table name
func (*EFMigrationsHistory) TableName() string {
	return TableNameEFMigrationsHistory
}
