// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCompany = "Companies"

// Company mapped from table <Companies>
type Company struct {
	ID   int32  `gorm:"column:Id;type:integer;primaryKey;autoIncrement:true" json:"Id"`
	Name string `gorm:"column:Name;type:text;not null" json:"Name"`
}

// TableName Company's table name
func (*Company) TableName() string {
	return TableNameCompany
}
