// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProject = "Projects"

// Project mapped from table <Projects>
type Project struct {
	ID        string    `gorm:"column:Id;type:uuid;primaryKey" json:"Id"`
	Name      string    `gorm:"column:Name;type:text;not null" json:"Name"`
	StartDate time.Time `gorm:"column:StartDate;type:date;not null" json:"StartDate"`
	EndDate   time.Time `gorm:"column:EndDate;type:date;not null" json:"EndDate"`
	CompanyID int32     `gorm:"column:CompanyId;type:integer;not null" json:"CompanyId"`
}

// TableName Project's table name
func (*Project) TableName() string {
	return TableNameProject
}
