// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSprint = "Sprints"

// Sprint mapped from table <Sprints>
type Sprint struct {
	ID        string    `gorm:"column:Id;type:uuid;primaryKey" json:"Id"`
	Name      string    `gorm:"column:Name;type:text;not null" json:"Name"`
	StartDate time.Time `gorm:"column:StartDate;type:date;not null" json:"StartDate"`
	EndDate   time.Time `gorm:"column:EndDate;type:date;not null" json:"EndDate"`
	ManagerID string    `gorm:"column:ManagerId;type:uuid;not null" json:"ManagerId"`
	ProjectID string    `gorm:"column:ProjectId;type:uuid;not null;default:00000000-0000-0000-0000-000000000000" json:"ProjectId"`
	TeamID    string    `gorm:"column:TeamId;type:uuid;not null;default:00000000-0000-0000-0000-000000000000" json:"TeamId"`
}

// TableName Sprint's table name
func (*Sprint) TableName() string {
	return TableNameSprint
}
