// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTaskStatus = "TaskStatuses"

// TaskStatus mapped from table <TaskStatuses>
type TaskStatus struct {
	ID   int32  `gorm:"column:Id;type:integer;primaryKey;autoIncrement:true" json:"Id"`
	Name string `gorm:"column:Name;type:text;not null" json:"Name"`
}

// TableName TaskStatus's table name
func (*TaskStatus) TableName() string {
	return TableNameTaskStatus
}
