// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTaskHistory = "TaskHistories"

// TaskHistory mapped from table <TaskHistories>
type TaskHistory struct {
	ID         string    `gorm:"column:Id;type:uuid;primaryKey" json:"Id"`
	TaskID     string    `gorm:"column:TaskId;type:uuid;not null" json:"TaskId"`
	ChangeDate time.Time `gorm:"column:ChangeDate;type:timestamp with time zone;not null" json:"ChangeDate"`
	NewStatus  string    `gorm:"column:NewStatus;type:text;not null" json:"NewStatus"`
	OldStatus  string    `gorm:"column:OldStatus;type:text" json:"OldStatus"`
}

// TableName TaskHistory's table name
func (*TaskHistory) TableName() string {
	return TableNameTaskHistory
}
