// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTask = "Tasks"

// Task mapped from table <Tasks>
type Task struct {
	ID           string `gorm:"column:Id;type:uuid;primaryKey" json:"Id"`
	Name         string `gorm:"column:Name;type:text;not null" json:"Name"`
	Description  string `gorm:"column:Description;type:text" json:"Description"`
	TaskTypeID   int32  `gorm:"column:TaskTypeId;type:integer;not null" json:"TaskTypeId"`
	TaskStatusID int32  `gorm:"column:TaskStatusId;type:integer;not null" json:"TaskStatusId"`
	DeveloperID  string `gorm:"column:DeveloperId;type:uuid" json:"DeveloperId"`
	SprintID     string `gorm:"column:SprintId;type:uuid" json:"SprintId"`
	ProjectID    string `gorm:"column:ProjectId;type:uuid" json:"ProjectId"`
}

// TableName Task's table name
func (*Task) TableName() string {
	return TableNameTask
}
