// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTaskType = "TaskTypes"

// TaskType mapped from table <TaskTypes>
type TaskType struct {
	ID   int32  `gorm:"column:Id;type:integer;primaryKey;autoIncrement:true" json:"Id"`
	Name string `gorm:"column:Name;type:text;not null" json:"Name"`
}

// TableName TaskType's table name
func (*TaskType) TableName() string {
	return TableNameTaskType
}
