// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTeam = "Teams"

// Team mapped from table <Teams>
type Team struct {
	ID        string `gorm:"column:Id;type:uuid;primaryKey" json:"Id"`
	Name      string `gorm:"column:Name;type:text;not null" json:"Name"`
	ManagerID string `gorm:"column:ManagerId;type:uuid;not null" json:"ManagerId"`
	ProjectID string `gorm:"column:ProjectId;type:uuid;not null;default:00000000-0000-0000-0000-000000000000" json:"ProjectId"`
}

// TableName Team's table name
func (*Team) TableName() string {
	return TableNameTeam
}
