// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "Users"

// User mapped from table <Users>
type User struct {
	ID                     string    `gorm:"column:Id;type:uuid;primaryKey" json:"Id"`
	Username               string    `gorm:"column:Username;type:text;not null" json:"Username"`
	PasswordHash           string    `gorm:"column:PasswordHash;type:text;not null" json:"PasswordHash"`
	Role                   string    `gorm:"column:Role;type:character varying(13);not null" json:"Role"`
	RefreshToken           string    `gorm:"column:RefreshToken;type:text" json:"RefreshToken"`
	RefreshTokenExpiryTime time.Time `gorm:"column:RefreshTokenExpiryTime;type:timestamp with time zone" json:"RefreshTokenExpiryTime"`
	Avatar                 string    `gorm:"column:Avatar;type:text" json:"Avatar"`
	PasswordSalt           string    `gorm:"column:PasswordSalt;type:text;not null" json:"PasswordSalt"`
	TeamID                 string    `gorm:"column:TeamId;type:uuid" json:"TeamId"`
	NeedResetPassword      bool      `gorm:"column:NeedResetPassword;type:boolean;not null" json:"NeedResetPassword"`
	Email                  string    `gorm:"column:Email;type:text;not null" json:"Email"`
	FirstName              string    `gorm:"column:FirstName;type:text;not null" json:"FirstName"`
	LastName               string    `gorm:"column:LastName;type:text;not null" json:"LastName"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
